### ISSUE TITLE
Ability to pass the run ID to the training script

### ISSUE THREAD

**Issue by swfearp** [guildai/guildai#153]
First of all, my team is very grateful for your work on this project; thank you. 

My question: Is it possible to pass the run ID to the training script so that generated files can be saved into a directory with the same ID? This would make it much easier for us to be able to go from comparing models in guild to pulling the weights and putting a model into our testing environment. 

Currently, we are logging the outputs then after comparing the runs we have to go through the logs and find where the model was saved. I see there is a section for files that have been generated by the run, but for MXNet this doesn't seem to ever find anything.

Alternatively, if there is already a better solution I would love to know how to implement it.

Thanks,
Sam

**Comment by gar1t** [comment]
Run ID is always available as the environment variable `RUN_ID`. You can get the run directory from the `RUN_DIR` environment variable.

E.g. as sample Guild file:

``` yaml
test:
  exec: bash -c 'echo $RUN_ID - $RUN_DIR'
```

That said, to save files to the run directory, simply create them with a relative path. Guild changes the working directory to the run directory for your script. This is a major design consideration that lets Guild associate generated files with each unique run directory.

For example, to write a file `hello.txt` to the run directory:

``` python
with open("hello.txt", "w") as f:
    f.write("hi!")
```

You can view the files associated with a run using the `ls` command:

``` shell
$ guild ls  # defaults to showing files for the latest run
```

It sounds like you're trying to do something using MXNet that looks for files somewhere. This could be a major point of confusion if you or MXNet is assuming that files are generated in a specific location and Guild, by changing the current directory, is misdirecting those files.

If you can elaborate on what sort of errors (specific messages are helpful if you're able to provide them) you're seeing, we can try to resolve the issue.

**Comment by swfearp** [comment]
Just being able to get `RUN_ID` using `os.getenv('RUN_ID')` solves my problem, thanks!
I didn't know about these environmental variables, is there a list of these?

**Comment by gar1t** [comment]
Unfortunately I'm seeing no docs covering this topic. I'll make sure those land in the upcoming release. Thanks for pointing that out!

Though just to nag a little, it's uncommon for a script to know or use the run ID. The goal is to support scripts that are independent of Guild - so that you and others can run them without Guild for dev purposes or just to not have to use a tool to do something simple like run a Python script :)

If your script is spending cycles trying to locate generated files using Guild specific environment variables, consider using relative paths - or use explicit paths specified by a command line arg.

For example, here's a training script that uses `argparse` to define a CLI, which includes the path where files should be generated:

``` python
import argparse
import my_model

p = argparse.add_argument(
    "--output-dir",
    default="output", 
    help="location of generated files")
args = p.parse_args()

my_model.train(args.output_dir)
```

Note there's no Guild-specific code in there! When you run the script, output lands in the `output` subdirectory. In the next step we configure the Guild op to use `.` (current directory).

Here's the Guild file:

``` yaml
train:
  main: train --output-dir .
```

When Guild runs a script, it changes the current directory to the unique run directory, so in this case `.` is the run directory. The script relies on `args.output_dir` so there's no need to look for `RUN_ID` or `RUN_DIR`.

Of course if you're doing something different, ignore this! I just don't want you do have to do a bunch of work in your code if you don't need to :)

**Comment by swfearp** [comment]
When we run experiments we put each generated model into separate directories each named with a random hash (mainly because we generate a lot of outputs). So this just enables us to use the guild id as the hash instead of having to cross-reference between two hashes.

Thanks for all your help, looking forward to seeing the global variable doc in an upcoming release.
