### ISSUE TITLE
guild run --rerun 0 doesn't work

### ISSUE THREAD

**Issue by thomsentner** [guildai/guildai#154]
I'm getting the following error:
`guild: could not find a run matching '0'`
`Try 'guild runs list' for a list.`

I've tried to look at the source code, but cannot quite figure out where `the special value 0` is handled.

**Comment by gar1t** [comment]
Thanks for the report and sorry about the long delay in replying!

A few things have changed since 0.6 and are in 0.7.0.rc10 (not released but will be out this week):

- `--rerun` is renamed to `--proto` (short for prototype) to better clarify its function vis-a-vis the similar sounding option `--restart`
- `--proto` no longer supports the special run ID `0`
- The role of special/weird IDs is replaced with the use of a new command `select`, which returns a run ID based on select criteria - this provides a lot more flexibility in specifying runs to restart or as prototypes

To start a new run using the latest run as a prototype, you'd use this:

```
$ guild run --proto `guild select`
```

See `guild select --help` for a list of options.

Note that this approach doesn't work with shells that don't support command substitution (e.g. Windows). The CLI may support an alternative approach that doesn't require command substitution.

**Comment by gar1t** [comment]
I'm going to close this as I believe the `--proto` option is what you want here. If that doesn't work as expected, please re-open or create a new issue so we can get it fixed. Thanks again for the report!
