### ISSUE TITLE
Precision-recall dashhboard not showing in tensorboard

### ISSUE THREAD

**Issue by casimp** [guildai/guildai#173]
Per-epoch precision-recall curves generated using the pr_curve plugin are not shown in tensorboard when monitored through Guild. This data is stored in tfevent files, which do not appear to have been carried across to the .guild/runs/{run_id} folder

**Comment by gar1t** [comment]
Thanks a lot for the report!

This is fixed in master and will be available in the next release (this week).

I created an issue resolution doc here, which is used to verify the bug in rc9:

https://github.com/guildai/issue-resolution/tree/master/173-precision-recall-dashhboard-not-showing-in-tensorboard

**Comment by casimp** [comment]
Fantastic, thanks for dealing with this so quickly! I look forward to using this when rc10 is released.

**Comment by gar1t** [comment]
Per https://my.guild.ai/t/precision-recall-dashboard-not-showing/155/2 is looks like we have more work on this one. Well, that's why they call it programming ;)

Are you able to recreate the success case following [these steps](https://github.com/guildai/issue-resolution/tree/master/173-precision-recall-dashhboard-not-showing-in-tensorboard)?

If that's working for you, but your specific case is not working, it'd be great to update that example with an operation that shows the failure. If you have some sample code, paste it here or via gist, or even smoother, PR for that example :)

**Comment by casimp** [comment]
Sorry for the slow reply. I'm able to recreate the success case, which is good news. I'll need a bit more time to dig around and work out what is happening with my specific case. Happy to create a PR once I've pared the issue down to something re-create able. I'll try to get that done today or tomorrow!

**Comment by casimp** [comment]
After some more digging I've realised that the issue I've had since rc10 is just related to changes to my codebase (I had stopped saving the pr event file to the correct location). I've updated my code and, as far as I can tell, this is all working. Sorry for any confusion and thanks for your help with this!

**Comment by gar1t** [comment]
Great - I'm glad this feature is working for you! TensorBoard's PR plugin is super useful.

**Comment by gar1t** [comment]
Should be fixed in 0.7.0. If you're still seeing this behavior, please feel free to re-open. Thanks again!
