### ISSUE TITLE
Guild treating string as list sometimes

### ISSUE THREAD

**Issue by holi-ampx** [guildai/guildai#193]
When presented with strings, that can be evaluated to be lists, guild assumesit is not a string flag, but a list (and then runs a batched evaluator).

Example yaml configuration:
```
- config: shared-flags
  flags:
    string_param: '[1, 2]'
```
Changing string_param to different forms, e.g. `'(1, 2)'`, `'1, 2'`, `'this should be string[1, 2]'` produces different results from `'[1, 2]'` (the only expected behavior is, that `[1,2]` unquoted will be treated as a list).

(The goal is to not pass a list to guild, but to pass some print-notes to the script, for example.)

**Comment by gar1t** [comment]
Thank you for the report!

The fix is in master and will be available in 0.7.0.rc10.

I created an issue resolution doc here:

https://github.com/guildai/issue-resolution/tree/master/193-guild-treating-string-as-list-sometimes

Your example is supported as well as setting list-as-str values on the command line this way:

    $ guild run test list_as_str="'[1,2,3]'"

**Comment by gar1t** [comment]
Fix is now available in 0.7.0. Thanks again!
