### ISSUE TITLE
EDITOR with VS Code not working on Windows

### ISSUE THREAD

**Issue by saratbhargava** [guildai/guildai#267]
> Guild uses the editor defined in VISUAL or EDITOR environment variables.

I had set the EDITOR variable to code in Windows 10. This opens up the file in the VS Code. But the file is immediately deleted and guild is auto-confirming the default values, So I am not able to change the values in the text editor.

**Comment by gar1t** [comment]
Okay - I take it back. I would not call this a bug. What you're seeing I believe is expected behavior.

Define `EDITOR` using the `code` command with the `-w` option (wait). This causes VS Code to block until you close the file. This is a requirement for the Guild interface to that file.

I'll update the topic on the user community in case that's helpful for others.

**Comment by saratbhargava** [comment]
Yes, it worked. Thank you.
