### ISSUE TITLE
Feature request: Path autocompletion

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#268]
We often run operations like
```bash
guild run predict_video -y path=<something>
``` 
It would be nice if bash/zsh/other could autocomplete this path when you press `tab`

**Comment by gar1t** [comment]
This is now [supported on bash](https://my.guild.ai/t/command-auto-completion-available-to-try-in-0-7-1-rc1/481). This should also work on zsh and fish.

I'll promote this content to proper docs so it's more visible.

**Comment by samedii** [comment]
Nice! Kind of obscure but maybe it is experimental and will be installed by default later?

**Comment by gar1t** [comment]
The approach of explicitly installing completion support is intentional. The feature is definitely not experimental at this point, at least on bash.

Python distributions typically don't modify user system environments, as is required for completion support. I'm not aware of any that do that anyway. I could see automatically installing completion support if Guild was installed using a system package manager (apt, brew, etc.) This is a bigger maintenance topic though.
