### ISSUE TITLE
Too many (default) arguments

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#27]
Default arguments to argparse are very long, resulting in the file name becoming too long when running optimizer gp (since it adds even default arguments to the file name):

`guild tensorboard` gives:

`
OSError: [Errno 36] File name too long: '/home/richard/anaconda3/.guild/runs/d000fe108c3f11e9b10ccfe26ce87b17' -> '/tmp/guild-tensorboard-t9bu1lbp/d000fe10 train.py 2019-06-11 13:59:33 gp+random anchor_height=46 anchor_width=368 batch_size=4 evaluation_batch_size=64 gradient_clipvalue=1.0 images_path=_..........._ labels_path=_............_csv learning_rate=0.001 max_epochs=1 oversample_factor=15 seed=71751 steps_per_epoch=2'
`

Guessing the suggested solution is to use a guild.yml-file to hide these arguments (images_path and labels_path)?

**Comment by gar1t** [comment]
You are indeed correct! Operations accept a `label` attribute that lets you define a custom label that is used instead of the default generated by the batch (i.e. optimized run).

Here's an example:

https://github.com/guildai/examples/tree/master/labels

Note that the "disabled" example (not setting a label at all) doesn't work in `0.6.3` - but `0.6.4` is on its way! In the meantime, you can prevent this huge label and file name problem by setting some non-blank label in the Guild file.

There's an outstanding issue on file names used for TensorBoard links as well but it's not here on GitHub - I'll add that so we can track.

**Comment by samedii** [comment]
I do not think it would make sense to set one label for all my GP runs. There is no problem with normal runs but when optimizing hyperparameters it adds all arguments (even if it is not optimizing them) to the name of the run

**Comment by gar1t** [comment]
The `label` attribute is intended to use flag references (i.e. `${FLAG}`) so you'd get a different label based on the flag value.

Are you suggesting that the batch label include only those flags that vary across runs, rather than include all flags? I think that makes sense. We could try that and see how it feels. What do think?

**Comment by samedii** [comment]
Yes, I think that might work :+1:

**Comment by gar1t** [comment]
The new behavior is available in `0.6.5` - a pre-release went out yesterday for testing.

Default labels for both trials and batch runs I think are more sensible now:

- By default, only non-default flag values show up in the default labels. In practice this seems to do a good job in distinguishing the run. This applies to batch runs now so that `-Fo` flags appear in the batch label by default.

- Previously the `--label` option applied to both trials and batches. Now there's a `--batch-label` option for run that lets you explicitly set the batch label, which is distinct from the trial labels.

Note that you can include a flag reference in a label using the `${FLAG_NAME}` syntax.

**Comment by samedii** [comment]
Awesome! Closing this
