### ISSUE TITLE
Flag recognition bug during remote run of nested op

### ISSUE THREAD

**Issue by ghwatson** [guildai/guildai#298]
Recently I was refactoring some code to use `flags-dest: args` (coming from `flags-dest: globals` where I didn't have this issue), and ran into a fairly specific bug involving an inconsistency between remote and local behaviour. Because of the required context for the bug to occur, I've distilled it out into a github repo to share with you:

https://github.com/ghwatson/guild_binaryflag_bug

If you setup a remote `myremote` and download the github repo, you should hopefully see the following behaviour:

Fail cases:
- `guild run nested_op DEVMODE=yes -r myremote`

Success cases:
- `guild run nested_op DEVMODE=yes`
- `guild run root_op DEVMODE=yes`
- `guild run root_op DEVMODE=yes -r myremote`
- `guild run nested_op -r myremote` 

The bug ultimately manifests as a complaint about the DEVMODE flag not being supported. There were also some warnings about flag detection on the imported file which may or may not be relevant.

It's interesting in that the bug hinges not only on the execution via remote and the positive binary flag, but also the line `import upstream_dep` inside the operation's python file.

Let me know what you think it might be and if there's a way to work around this!

**Comment by gar1t** [comment]
This should be considered a model issue. Providing working code that demonstrates the issue is the fastest and clearest path to a resolution!

This PR should explain the resolution:

https://github.com/ghwatson/guild_binaryflag_bug/pull/1

For the record here, the root problem is not the argparse behavior but the fact that there's a missing module, which Guild does not package. The warnings are there in the output, but it's not obvious. Guild should arguably fail outright with the import error and not attempt to run the code. But this error occurs when Guild is importing flags, not when it runs the code. I'm inclined to keep this as a warning as there are myriad ways that Guild might fail to import flags. The real problem is in the running of the operation, which Guild would have gotten to if you bypassed the flag validation using `--force-flags` option.

To run remotely, all modules must be inside a Python package. That's the only way to install them in a "site" location. This is a Python constraint.

The PR shows the modifications.

This does go against the "don't change your code" rule that Guild prefers. However, the changes here are Pythonic and not Guild specific (other than the fact that Guild uses Python package installs to implement its remote support).

**Comment by ghwatson** [comment]
Ah this is great! Thank you for taking the time to fix and also explain. Pythonic changes not a problem at all.

Closing issue.
