### ISSUE TITLE
Extremely long operation names when viewing from different machine

### ISSUE THREAD

**Issue by AndrewPaulChester** [guildai/guildai#34]
I recently transferred my guild runs to a different machine using the export/import functionality.
When viewing runs with guild view or guild runs list commands, the operation names are prepended with the relative path to the relevant guild.yml file. Since the operations I imported are from a completely different file system, it tries to include the full path, which is extremely long and prevents me from seeing any relevant details (example below). I can see why having the path may be useful in some instances (although I would be happy to remove it entirely), but is there any way of resetting these paths to the relevant folder on my current machine?

```    
[23:3daaad98]  dqn:train
[24:d61e2fa6]  dqn:train                                   
[25:7bf8346e]  .../andrew/Documents/PhD/symbolic-goal-generation/ikostrikov:trai
[26:7bf83220]  .../andrew/Documents/PhD/symbolic-goal-generation/ikostrikov:trai  
[27:7bd80658]  .../andrew/Documents/PhD/symbolic-goal-generation/ikostrikov:trai  
```

**Comment by gar1t** [comment]
Comment re op format (independent of the import issue raised but related to the long display name)...

It's not clear there's any real advantage to full path following `.../`. The pattern `.../` is simply a replacement for the backward path `../../../` (and so on) to the common ancestor. The original thinking was, as the path shared a common ancestor, it would be helpful to see the full path from that ancestor.

In practice, I don't know if that path provides enough signal to overcome the noise. In my eye I just see "bunch of text".

In conjunction with the import fix, we should consider using `.../` with the last directory only. So the above example would be:

```
[23:3daaad98]  dqn:train
[24:d61e2fa6]  dqn:train                                   
[25:7bf8346e]  .../symbolic-goal-generation/ikostrikov:train
[26:7bf83220]  .../symbolic-goal-generation/ikostrikov:train
[27:7bd80658]  .../symbolic-goal-generation/ikostrikov:train
```

One could still get the full path to the operation via `guild runs info`.

Note again, this comment is not related to the import problem described above. It does mitigate the extremely long operation name problem.

**Comment by gar1t** [comment]
Re the import problem, this is tricky. Guild currently saves the full absolute path to the operation source in the run `opref` attribute (under `RUN_DIR/.guild/opref`). This is Guild's link to the defining operation (e.g. Guild file, package, script, etc.) If this reference is broken, it's generally not a problem as the run is self-sufficient. There are limited cases where Guild will use that reference to get the latest config for the run operation (e.g. when comparing runs to find the current list of compare specs).

On export and import, obviously the absolute path scheme breaks across systems. Even a relative path scheme breaks. Really we don't want to include the local opref data in the exported run as it no longer applies.

The tricky part is that this now complicates export, which is otherwise a trivial copy of the unmodified directory. There is no simple way to modify the copy in flight and preserve the convenience of file system copies (e.g. using rsync, scp, cp, etc.) This would require a staging area for each copy.

A few notes that occur to me:

- oprefs should include relative paths to the defining operation/scripts - this doesn't solve our problem but it seems more correct than storing these refs as absolute paths
- Don't attempt to modify runs on export - modifying targets has widespread complexity and performance implications (I think)
- If we're going to fix the opref, do it on import - we can apply these updates after any generic file copy operation
- (Possibly) provide a command to associate run(s) with a project - this logic could potentially be applied with an option to the import command (e.g. `guild import LOCATION --adopt` - or something similar) or perhaps as default with an option to skip the logic (completely unsure here)

**Comment by gar1t** [comment]
Okay, Guild got a bit of an overhaul in the way it displays operations.

https://github.com/guildai/issues/tree/master/34-long-operation-names

This will land in 0.6.6 and is available for preview in 0.6.6.dev5.

Note that these changes to not address the problem of orphaned or misplaced runs due to path differences across systems. This is strictly the "op names too long" problem.

I'll create a separate issue for orphaned runs.

**Comment by AndrewPaulChester** [comment]
Tested this - I like the new display (especially the fact the path comes after the model name). One thing to note is that the location qualifier is not displayed for batch runs - I'm not sure if this is expected or not, but doesn't bother me at all.

**Comment by gar1t** [comment]
Great! I'm glad you like the new display. Thanks for the heads up on the batch runs. There's a technical/pedantic reason there's no path there (technical that operation is the batch, which is built-in and doesn't have a path) but I think that's confusing :) I'll get that into the final of 0.6.6.
