### ISSUE TITLE
boolean flag with click reports wrong value 

### ISSUE THREAD

**Issue by vitalwarley** [guildai/guildai#366]
Related, but for `ArgumentParser`: #124 

MRE: [examples/flags/args_click.py](https://github.com/guildai/guildai/blob/20a13ac91d351fbd1a7c144638b6643dd243bf21/examples/flags/args_click.py)

## Checks

```
λ guild check                     
guild_version:             0.8.0
guild_install_location:    /home/warley/.virtualenvs/guildai/lib/python3.10/site-packages/guild
guild_home:                /home/warley/.virtualenvs/guildai/.guild
guild_resource_cache:      /home/warley/.virtualenvs/guildai/.guild/cache/resources
installed_plugins:         config_flags, cpu, dask, disk, dvc, exec_script, gpu, ipynb, keras, memory, perf, python_script, queue, skopt
python_version:            3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
python_exe:                /home/warley/.virtualenvs/guildai/bin/python
platform:                  Linux 5.14.9-arch1-g14-3 x86_64
psutil_version:            5.9.0
tensorboard_version:       2.8.0
cuda_version:              11.6.112
nvidia_smi_version:        510.54
latest_guild_version:      0.8.0
```

## Tests

- `b` default is `False`, but gets evaluated to `True`.

```
╚═╡(guildai) [15:12] λ guild run args-click-default
Refreshing flags...
You are about to run args-click-default
  b: no
  c: red
  f: 1.1
  i: 1
  s: hello
Continue? (Y/n) 
Flags: 1 1.1 True hello red
```

- `b=0` gives `True`
- `b=1` gives `False`
- `b=True` gives `False`
- `b=False` gives `True`

Am I missing something?

**Comment by vitalwarley** [comment]
I would happily try a PR if you guys point me the way to solve this bug. :)

**Comment by msarahan** [comment]
Off the top of my head, it doesn't look the same as #124. If I read that issue correctly, the issue there is that non-empty strings get treated as True. In that issue, `foo` is only coming out as True. Here it looks like things are being read correctly, but are being inverted. I'm out of time for this afternoon, but I'll revisit this tomorrow morning.

**Comment by msarahan** [comment]
Here's what I think is happening.

1. The flags are loaded from the parsed click inputs: https://github.com/guildai/guildai/blob/master/guild/plugins/click_flags.py#L156-L157

2. The flags are matched against that switch default state: https://github.com/guildai/guildai/blob/master/guild/op_cmd.py#L111-L115

With the default click behavior, the is_flag=True setting has a default of False. That means our logic in (2) provides the --b flag to the python command line inverted from what we expect.

I think the answer might be to treat args_switch as an indicator of whether the arg is a boolean, not what the default value of that boolean is. In other words, in (1), it should not be set to `params.default`, but instead should be `True`

If you would like to try this and submit a PR with your findings, I'd greatly appreciate it.

EDIT: that was not the right fix. I think the right fix is instead to negate param.default when reading in the click parameters.

**Comment by vitalwarley** [comment]
Very nice, @msarahan. Thanks for the info. I will surely try it ASAP.

**Comment by vitalwarley** [comment]
@msarahan, I have been trying to understand the flow from CLI execution to the code you pointed me. 

First of all, if I add  

```yaml
  flags:
    b: 
      arg-switch: yes
```

to the op in `guild.yml`, the problem disappears. No patches are needed. 

I have a couple of questions, though

1) From what I understand, adding `arg-switch` is an explicitly defined behavior. guild should have done that implicitly, right?
2) How do plugins work with guildai? 
    - I couldn't debug the fix you suggested in `guild/plugins/click_flags.py`. Negating `param.default` didn't work, but I think it wasn't called.
       - I debugged with `python -m trace -T ../../guild/scripts/guild run args-click-default >> trace.txt` and didn't find `_maybe_apply_flag` function.
    - I saw `entry_point_util.EntryPointResources` in `guild/plugins/python_script.py` and related files, but unfortunately, I couldn't understand... yet.
3) How do you perform local tests in your dev code for guildai?
    - I did this: `../../guild/scripts/guild run args-click-default`
    - Is it right?

I think I need more time and your help to be comfortable with any modifications I may make. Please, let me know if there is anything I can learn to proper understand the context of this issue. Thanks!

**Comment by msarahan** [comment]
I have only recently joined the project myself, and I'm not an expert. Here's some thoughts.

* Setting arg-switch to yes is equivalent to hard-coding it to True (my first idea) - so maybe that is a fix after all.
* I agree that guild should have set arg-switch properly implicitly as part of importing the flags from the python script. It is setting it, but just not correctly (I think). There's two values that need to be considered:
  1. The "polarity" of the switch - whether it defaults to True or False
  2. The value - If you set a value of True, does that toggle the switch to the value opposite its default? This is what the logic in https://github.com/guildai/guildai/blob/master/guild/op_cmd.py#L111-L115 is attempting to do. It's saying "what is the default value?" and then "does my set value match that default value?" This is broken, though, because if the default is False, and we set a value of False, that then evaluates to passing the flag to the python script (which is equivalent to True).

If switches only ever had one polarity (always default False or always default True, with default False being more common), this would be easier to think about.

> How do plugins work with guildai?

Sorry, that was not the right path to lead you down. I had made several changes at once, and this one looked like the most correct fix but you're right, it is not involved in this example. It may still be worth keeping in mind, but let's shelve it for now.

The main thing that we have to get right is the polarity/value relationship described above. What makes it even more complicated is that we must fix things for scripts that use click without breaking things for scripts that use argparse. We'll definitely need to have this stuff well-tested before merging.

> How do you perform local tests in your dev code for guildai?
I did this: ../../guild/scripts/guild run args-click-default
Is it right?

I have a couple of ways I've found to debug. One is to put in pdb (or ipdb) lines, like so:

`import pdb; pdb.set_trace()`

I then run the script like you do, but I'll get a debugging prompt where I want it.

If you use VS Code, you can use its built-in debugger. You need to launch the "run" command. There's a couple of examples in https://github.com/guildai/guildai/blob/master/.vscode/launch.json#L14 - just edit the cwd and the operation name. Then you should be able to set breakpoints in VS Code's gutter (to the left of the line numbers) and have that work.

The test suite is all defined in doctest format in the guild/tests folder. You can run them with `make check` in the root of the repo, or you can use pytest in the root of the repo. It seems like the right file for these tests is https://github.com/guildai/guildai/blob/master/guild/tests/import-flags.md, but I don't see anything in there about click. We'll probably need to add tests. Hopefully we can copy and adapt the existing argparse tests.

To run just the one test file:

`pytest -k import-flags` or `make check TEST="import-flags"`

If you do use pdb and pytest together, note that you'll need to use the --pdb flag with pytest in order to allow the breakpoints to work, otherwise it'll just crash when it hits your breakpoint.

I'm happy to help on any part of this - just let me know when you feel like you're stuck or you've had enough.

**Comment by msarahan** [comment]
To clarify the "polarity" idea: what is provided by the python script is the default value. When a user passes a flag value, that must be reconciled with the default value, such that the `--b` text gets emitted when the flag value does not match the default value, but not when the flag value does match the default value.

**Comment by msarahan** [comment]
I put up a PR that fixes the issue for click. I have no idea whether it breaks other things, and it feels like something that might break tests. Hopefully it does, because the tests are wrong and need to be corrected! I'm going to run more tests and write a few as well.

**Comment by msarahan** [comment]
These are backwards: https://github.com/guildai/guildai/blob/master/guild/plugins/import_argparse_flags_main.py#L165-L168

store_true means the flag defaults to False, and specifying `--b` would change it to true. That's the root of all the confusion here.

**Comment by msarahan** [comment]
The reason why you can't debug click_util and argparse stuff is because it is done in a subprocess: https://github.com/guildai/guildai/blob/master/guild/plugins/python_script.py#L355

**Comment by msarahan** [comment]
And one other thing - the results of getting the flags for a given operation are cached. That cache lives somewhere like this: `/home/msarahan/mambaforge/envs/guildai_38/.guild/cache/import-flags/ac38e597955a8351defb94f14f6cae05` If you don't clear that cache, then the flag import code won't run, and you will be confused by stale values.

**Comment by msarahan** [comment]
fixed by https://github.com/guildai/guildai/commit/3ece0c7656eb25199bb181e12762c38c3213748a
