### ISSUE TITLE
Some flags with argparse actions don't get detected

### ISSUE THREAD

**Issue by abogatskiy** [guildai/guildai#378]
If I have a flag like 
````
parser.add_argument('--foo', action=argparse.BooleanOptionalAction, default=True)`
````

in my args, `guild` doesn't import this flag, so it doesn't show up in `guild run --test-flags`. The alternative is the standard implementation from before Python 3.9:

```
parser.add_argument('--foo', dest='foo', action='store_true')
parser.add_argument('--no-foo', dest='foo', action='store_false')
parser.set_defaults(foo=True)
````
    
In this case the flag does get imported, but the problem is that `--no-foo` also gets imported as a separate flag and the default value gets messed up (both have `default: True` according to `guild run --test-flags`).

Finally, flags setting a constant through `action=store_const` also seem to be unsupported: 

````
parser.add_argument('--foo1', dest='foo', action='store_const', const=1)
parser.add_argument('--foo2', dest='foo', action='store_const', const=2)
parser.set_defaults(foo=1)
````

neither `foo1`, `foo2`, nor `foo` show up in `guild run --test-flags`. Am I missing something?

**Comment by msarahan** [comment]
We're catching up with newer versions of Python (3.9+), and that might explain the failure to import the new style flag. Definitely a bug.

Regarding the default value earlier alternative standard, there was a fix in https://github.com/guildai/guildai/commit/a7791729037511b50ad8b754e62760a92d9fede2, but that applied to Click-based CLIs. This may be something separate. Guild may not correctly handle the case with both flags, because it associates the one flag name with the last-parsed action (store_false means default is True). If possible, please avoid providing both `--foo` and `--no-foo`, and allow the default to be parsed as the inverse of your action. I would not provide `set_defaults` either.

store_const is something I'm not familiar with yet, but I'll take a look to see if I can understand what might be happening here. It seems like unparsed flags should show a warning or error, but that's just my gut feeling, not an expectation based on experience.

**Comment by gar1t** [comment]
I would just say that Guild isn't (yet) supporting `.BooleanOptionalAction` types - it's missing this feature and not a bug but this is hair splitting :)

We'll add support for this in the next release, which should go out this week. Stay tuned.
