### ISSUE TITLE
Rerun parameter sweep only for runs that resulted in an error

### ISSUE THREAD

**Issue by jjakenichol** [guildai/guildai#456]
Hi,

I had a parameter sweep that failed on specific parameters. Say I've fixed the issue and I want to run again only on the parameters in` guild runs --error`. Is there an easy way to do that? It would be time consuming to run entire parameter sweep again or cherry pick the specific parameter combinations that returned an error.

The specific case that led to this question is that I was mistakenly running a parameter sweep on a remote server without tmux. When my connection to the remote server was dropped, it made the currently running experiments return an error and it seems that several staged runs disappeared, but most were stopped. I was running using the dask scheduler, so several runs were killed and marked error. I wasn't running any checkpointing because these are relatively fast models to train.

Thank you

**Comment by gar1t** [comment]
Hello! Guild doesn't support a command for this directly but you can use a bit of bash to accomplish it:

```
for id in `guild select --error --all`; do guild run --restart $id --background -y; done
```

Disappearing staged runs is concerning though! The only case where I could see that is that the staged runs were started (a background queue will do that) and ALSO the operation is configured with `delete-on-success`. Otherwise Guild will not delete a run, staged or otherwise. It sounds like that might be hard to track down at this point, but if you spot this again, I'd be curious to know.

**Comment by jjakenichol** [comment]
Thank you that is exactly what I needed. It's possible the runs didn't get staged; I can't say I was careful to double check that staging wasn't interrupted. I'll let you know if I notice it again.
